(()=>{
'use strict';
if(window.__TIA_TATI_REMAINING_V41__)return;window.__TIA_TATI_REMAINING_V41__=true;
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const breatheKey='tiaTatiBreatheV41',physicalKey='tiaTatiPhysicalV41';
const breatheCfg={mode:'calm',cycles:5,pace:'natural'};
const physicalCfg={profile:'guided',checkpoints:3,title:'Circuito de movimento'};
try{Object.assign(breatheCfg,JSON.parse(localStorage.getItem(breatheKey)||'{}'));}catch(_){}
try{Object.assign(physicalCfg,JSON.parse(localStorage.getItem(physicalKey)||'{}'));}catch(_){}
const saveBreathe=()=>{try{localStorage.setItem(breatheKey,JSON.stringify(breatheCfg));}catch(_){}};
const savePhysical=()=>{try{localStorage.setItem(physicalKey,JSON.stringify(physicalCfg));}catch(_){}};
function hideScreens(){qa('.screen').forEach(x=>x.classList.remove('active'));}
function setBottomHome(){qa('#bottomNav button').forEach(b=>b.classList.toggle('active',b.dataset.nav==='home'));}
function showHome(){q('#breatheV41Overlay')?.remove();q('#physicalV41Overlay')?.remove();document.body.style.overflow='';hideScreens();q('#screen-home')?.classList.add('active');setBottomHome();window.scrollTo({top:0,behavior:'smooth'});}
function saveStandaloneReport(activity,started,interactions,extra={}){
 try{
  const key='tiaTatiV12Reports';const prefs=JSON.parse(localStorage.getItem('tiaTatiV12Prefs')||'{}');const list=JSON.parse(localStorage.getItem(key)||'[]');
  list.unshift({id:Date.now(),date:new Date().toISOString(),activities:[activity],duration:Math.max(1,Math.round((Date.now()-started)/60000)),interactions,assists:0,collisions:0,checkpoints:extra.checkpoints||0,context:prefs.context||'APAE',observation:'',...extra});
  localStorage.setItem(key,JSON.stringify(list.slice(0,30)));
 }catch(_){}
}

function ensureBreatheSetup(){
 if(q('#screen-breathesetup'))return;
 const s=document.createElement('section');s.className='screen breathe-v41-setup';s.id='screen-breathesetup';
 s.innerHTML=`
 <div class="v41-head"><button class="back-btn v41-breathe-home" type="button">←</button><div><span class="kicker">PAUSA + AUTORREGULAÇÃO</span><h2>Respira Comigo</h2><p>Uma pausa guiada com opção acolhedora ou visual jovem.</p></div><div class="v41-tutor"><img src="assets/relax.webp" alt="Tia Tati"><span>Sem pressa. Só acompanhe o ritmo. 💗</span></div></div>
 <section class="breathe-v41-hero panel"><div><span class="mission-badge">🌿 RESPIRA COMIGO</span><h1>Pausa. Foco.<br><em>Recomeço.</em></h1><p>Ritmo visual para inspirar e soltar o ar com calma, sem competição e sem prender a respiração.</p><div class="v41-pills"><span>🌿 Pausa</span><span>👀 Foco visual</span><span>🫁 Ritmo</span><span>💗 Autonomia</span></div></div><div class="breathe-v41-orbit"><img src="assets/relax.webp" alt="Tia Tati"><i></i><b>RESPIRA</b></div></section>
 <section class="v41-section"><div class="road-v18-section-title"><span>1</span><div><strong>Escolha a experiência</strong><small>A mesma proposta com linguagens diferentes.</small></div></div><div class="v41-grid three">
  <button class="v41-choice" data-breathe-mode="calm" type="button"><span>🌿</span><strong>Calma</strong><small>Visual suave e acolhedor.</small></button>
  <button class="v41-choice" data-breathe-mode="focus" type="button"><span>🎧</span><strong>Focus</strong><small>Visual limpo para adolescentes.</small></button>
  <button class="v41-choice young" data-breathe-mode="reset" type="button"><span>⚡</span><strong>Reset</strong><small>Pausa jovem em tons neon.</small></button>
 </div></section>
 <section class="v41-section"><div class="road-v18-section-title"><span>2</span><div><strong>Ritmo</strong><small>Sem retenção do ar.</small></div></div><div class="v41-grid three">
  <button class="v41-choice" data-breathe-pace="slow" type="button"><strong>Suave</strong><small>5 s inspirar • 6 s soltar</small></button>
  <button class="v41-choice" data-breathe-pace="natural" type="button"><strong>Natural</strong><small>4 s inspirar • 5 s soltar</small></button>
  <button class="v41-choice" data-breathe-pace="active" type="button"><strong>Dinâmico</strong><small>3 s inspirar • 4 s soltar</small></button>
 </div></section>
 <section class="v41-section"><div class="road-v18-section-title"><span>3</span><div><strong>Ciclos</strong><small>Escolha uma pausa curta ou mais longa.</small></div></div><div class="v41-grid three">
  <button class="v41-choice" data-breathe-cycles="3" type="button"><strong>3 ciclos</strong><small>Curto</small></button><button class="v41-choice" data-breathe-cycles="5" type="button"><strong>5 ciclos</strong><small>Moderado</small></button><button class="v41-choice" data-breathe-cycles="7" type="button"><strong>7 ciclos</strong><small>Mais tempo</small></button>
 </div></section>
 <div class="v41-note panel"><span>💗</span><p><strong>Sem desempenho para comparar.</strong><br>O objetivo é acompanhar um ritmo confortável. A fisioterapeuta pode interromper ou adaptar a atividade a qualquer momento.</p></div>
 <div class="v41-dock"><div><small>Pronto para a pausa</small><strong id="breatheV41Summary"></strong></div><button class="primary" id="breatheV41Start" type="button">🌿 Começar</button></div>`;
 q('#screen-game')?.parentNode?.insertBefore(s,q('#screen-game'));
 s.addEventListener('click',e=>{
  const m=e.target.closest('[data-breathe-mode]');if(m){breatheCfg.mode=m.dataset.breatheMode;saveBreathe();syncBreathe();return;}
  const p=e.target.closest('[data-breathe-pace]');if(p){breatheCfg.pace=p.dataset.breathePace;saveBreathe();syncBreathe();return;}
  const c=e.target.closest('[data-breathe-cycles]');if(c){breatheCfg.cycles=Number(c.dataset.breatheCycles)||5;saveBreathe();syncBreathe();}
 });
 q('.v41-breathe-home',s).onclick=showHome;q('#breatheV41Start',s).onclick=startBreathe;syncBreathe();
}
function syncBreathe(){
 const s=q('#screen-breathesetup');if(!s)return;qa('[data-breathe-mode]',s).forEach(x=>x.classList.toggle('active',x.dataset.breatheMode===breatheCfg.mode));qa('[data-breathe-pace]',s).forEach(x=>x.classList.toggle('active',x.dataset.breathePace===breatheCfg.pace));qa('[data-breathe-cycles]',s).forEach(x=>x.classList.toggle('active',Number(x.dataset.breatheCycles)===Number(breatheCfg.cycles)));
 const mode={calm:'Calma',focus:'Focus',reset:'Reset'}[breatheCfg.mode]||'Calma',pace={slow:'Suave',natural:'Natural',active:'Dinâmico'}[breatheCfg.pace]||'Natural';const t=q('#breatheV41Summary',s);if(t)t.textContent=`${mode} • ${pace} • ${breatheCfg.cycles} ciclos`;
}
function showBreatheSetup(mode){ensureBreatheSetup();if(mode)breatheCfg.mode=mode;saveBreathe();syncBreathe();hideScreens();q('#screen-breathesetup')?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}
function startBreathe(){
 q('#breatheV41Overlay')?.remove();const mode=breatheCfg.mode,cycles=Number(breatheCfg.cycles)||5;const times={slow:[5000,6000],natural:[4000,5000],active:[3000,4000]}[breatheCfg.pace]||[4000,5000];const started=Date.now();
 const wrap=document.createElement('div');wrap.id='breatheV41Overlay';wrap.className='breathe-v41-overlay '+mode;wrap.innerHTML=`<div class="bv41-top"><div class="bv41-tati"><img src="assets/relax.webp" alt="Tia Tati"><div><small>TIA TATI</small><strong>Acompanhe a luz no seu ritmo.</strong><em>Sem prender o ar 💗</em></div></div><div class="bv41-count"><b id="bv41Cycle">1</b> / ${cycles}</div><div class="bv41-actions"><button id="bv41Back" type="button">←</button><button id="bv41Pause" type="button">⏸️</button></div></div><div class="bv41-stage"><div class="bv41-grid"></div><div class="bv41-ring"><div class="bv41-core"><b id="bv41Word">PRONTO</b><span id="bv41Seconds"></span></div></div><div class="bv41-caption">Toque em começar quando estiver confortável.</div><button class="bv41-start" id="bv41Go" type="button">Começar</button><div class="bv41-finish"><div><span>✨</span><h3>Pausa concluída</h3><p>Bom trabalho. Continue quando estiver pronto.</p><button class="primary" id="bv41Done" type="button">Voltar</button></div></div></div><div class="bv41-footer"><span></span></div>`;document.body.appendChild(wrap);document.body.style.overflow='hidden';
 const ring=q('.bv41-ring',wrap),word=q('#bv41Word',wrap),secs=q('#bv41Seconds',wrap),caption=q('.bv41-caption',wrap),fill=q('.bv41-footer span',wrap),finish=q('.bv41-finish',wrap);let cycle=0,paused=false,running=false,ended=false,timer=null,tick=null,phaseEnd=0,remaining=0,currentPhase='';
 const clear=()=>{clearTimeout(timer);clearInterval(tick);timer=tick=null;};
 const countdown=(ms)=>{clearInterval(tick);phaseEnd=Date.now()+ms;const draw=()=>{const left=Math.max(0,phaseEnd-Date.now());secs.textContent=Math.max(1,Math.ceil(left/1000))+' s';};draw();tick=setInterval(draw,180);};
 const phase=(kind,ms,next)=>{if(ended)return;currentPhase=kind;remaining=ms;ring.classList.remove('inhale','exhale');void ring.offsetWidth;ring.classList.add(kind);ring.style.setProperty('--phase-ms',ms+'ms');word.textContent=kind==='inhale'?'INSPIRE':'SOLTE';caption.textContent=kind==='inhale'?'Puxe o ar suavemente pelo nariz.':'Solte o ar devagar, sem forçar.';countdown(ms);timer=setTimeout(next,ms);};
 const runCycle=()=>{if(ended)return;if(cycle>=cycles){ended=true;clear();fill.style.width='100%';finish.classList.add('show');saveStandaloneReport('Respira Comigo',started,cycles,{breatheMode:mode,breatheCycles:cycles});return;}q('#bv41Cycle',wrap).textContent=cycle+1;phase('inhale',times[0],()=>phase('exhale',times[1],()=>{cycle++;fill.style.width=(cycle/cycles*100)+'%';runCycle();}));};
 q('#bv41Go',wrap).onclick=e=>{if(running)return;running=true;e.currentTarget.remove();runCycle();};
 q('#bv41Pause',wrap).onclick=e=>{if(!running||ended)return;paused=!paused;e.currentTarget.textContent=paused?'▶️':'⏸️';if(paused){remaining=Math.max(500,phaseEnd-Date.now());clear();ring.style.animationPlayState='paused';caption.textContent='Pausado. Continue quando quiser.';}else{ring.style.animationPlayState='running';phase(currentPhase,remaining,()=>{if(currentPhase==='inhale')phase('exhale',times[1],()=>{cycle++;fill.style.width=(cycle/cycles*100)+'%';runCycle();});else{cycle++;fill.style.width=(cycle/cycles*100)+'%';runCycle();}});}};
 q('#bv41Back',wrap).onclick=()=>{ended=true;clear();document.body.style.overflow='';wrap.remove();showBreatheSetup();};q('#bv41Done',wrap).onclick=()=>{document.body.style.overflow='';wrap.remove();showBreatheSetup();};
}

function ensurePhysicalSetup(){
 if(q('#screen-physicalsetup'))return;const s=document.createElement('section');s.className='screen physical-v41-setup';s.id='screen-physicalsetup';s.innerHTML=`
 <div class="v41-head"><button class="back-btn v41-physical-home" type="button">←</button><div><span class="kicker">TELA + MOVIMENTO REAL</span><h2>Missão no Mundo Real</h2><p>O app organiza o percurso; a tarefa física continua sendo definida pela fisioterapeuta.</p></div><div class="v41-tutor"><img src="assets/guide.webp" alt="Tia Tati"><span>Pronto para sair da tela? 👣</span></div></div>
 <section class="physical-v41-hero panel"><div><span class="mission-badge">👣 MOVIMENTO REAL</span><h1>Da tela para<br><em>o movimento.</em></h1><p>Checkpoints visuais para acompanhar circuitos físicos, tarefas funcionais e atividades orientadas presencialmente.</p><div class="v41-pills"><span>👣 Movimento</span><span>🧠 Sequência</span><span>✅ Autonomia</span><span>🏁 Progresso</span></div></div><div class="physical-v41-map"><i class="p1"></i><i class="p2"></i><i class="p3"></i><span>START</span><b>🏁</b></div></section>
 <section class="v41-section"><div class="road-v18-section-title"><span>1</span><div><strong>Escolha o visual</strong><small>Para diferentes idades sem mudar a proposta terapêutica.</small></div></div><div class="v41-grid two"><button class="v41-choice" data-physical-profile="guided" type="button"><span>👣</span><strong>Circuito Guiado</strong><small>Claro, simples e acolhedor.</small></button><button class="v41-choice young" data-physical-profile="quest" type="button"><span>🏁</span><strong>Move Quest</strong><small>Visual jovem com checkpoints.</small></button></div></section>
 <section class="v41-section"><div class="road-v18-section-title"><span>2</span><div><strong>Checkpoints</strong><small>Quantas etapas serão confirmadas na tela?</small></div></div><div class="v41-grid three"><button class="v41-choice" data-physical-checkpoints="3" type="button"><strong>3</strong><small>Curto</small></button><button class="v41-choice" data-physical-checkpoints="5" type="button"><strong>5</strong><small>Moderado</small></button><button class="v41-choice" data-physical-checkpoints="7" type="button"><strong>7</strong><small>Mais etapas</small></button></div></section>
 <section class="v41-section"><label class="physical-v41-label"><span>3</span><div><strong>Nome do circuito</strong><small>Ex.: circuito de alcance, percurso funcional, estação motora.</small></div></label><input id="physicalV41Title" class="physical-v41-input" maxlength="52" value="Circuito de movimento"></section>
 <div class="v41-note panel"><span>🧑‍⚕️</span><p><strong>Orientação presencial.</strong><br>O aplicativo não escolhe nem avalia o exercício físico. Ele apenas mostra o checkpoint e registra a confirmação manual.</p></div>
 <div class="v41-dock"><div><small>Pronto para o circuito</small><strong id="physicalV41Summary"></strong></div><button class="primary" id="physicalV41Start" type="button">👣 Iniciar percurso</button></div>`;
 q('#screen-game')?.parentNode?.insertBefore(s,q('#screen-game'));s.addEventListener('click',e=>{const p=e.target.closest('[data-physical-profile]');if(p){physicalCfg.profile=p.dataset.physicalProfile;savePhysical();syncPhysical();return;}const c=e.target.closest('[data-physical-checkpoints]');if(c){physicalCfg.checkpoints=Number(c.dataset.physicalCheckpoints)||3;savePhysical();syncPhysical();}});q('#physicalV41Title',s).addEventListener('input',e=>{physicalCfg.title=e.target.value.trim()||'Circuito de movimento';savePhysical();syncPhysical();});q('.v41-physical-home',s).onclick=showHome;q('#physicalV41Start',s).onclick=startPhysical;syncPhysical();
}
function syncPhysical(){const s=q('#screen-physicalsetup');if(!s)return;qa('[data-physical-profile]',s).forEach(x=>x.classList.toggle('active',x.dataset.physicalProfile===physicalCfg.profile));qa('[data-physical-checkpoints]',s).forEach(x=>x.classList.toggle('active',Number(x.dataset.physicalCheckpoints)===Number(physicalCfg.checkpoints)));const inp=q('#physicalV41Title',s);if(inp&&document.activeElement!==inp)inp.value=physicalCfg.title||'Circuito de movimento';const t=q('#physicalV41Summary',s);if(t)t.textContent=`${physicalCfg.profile==='quest'?'Move Quest':'Circuito Guiado'} • ${physicalCfg.checkpoints} checkpoints`;}
function showPhysicalSetup(profile){ensurePhysicalSetup();if(profile)physicalCfg.profile=profile;savePhysical();syncPhysical();hideScreens();q('#screen-physicalsetup')?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}
function startPhysical(){
 q('#physicalV41Overlay')?.remove();const profile=physicalCfg.profile,count=Number(physicalCfg.checkpoints)||3,title=(physicalCfg.title||'Circuito de movimento').trim();const started=Date.now();const wrap=document.createElement('div');wrap.id='physicalV41Overlay';wrap.className='physical-v41-overlay '+profile;wrap.innerHTML=`<div class="pv41-top"><div class="pv41-tati"><img src="assets/guide.webp" alt="Tia Tati"><div><small>TIA TATI</small><strong>${profile==='quest'?'MOVE QUEST':'MISSÃO NO MUNDO REAL'}</strong><em>A tarefa é orientada presencialmente.</em></div></div><div class="pv41-actions"><button id="pv41Back" type="button">←</button><button id="pv41Pause" type="button">⏸️</button></div></div><div class="pv41-stage"><div class="pv41-route"><span id="pv41Route"></span></div><div class="pv41-card"><span class="pv41-kicker">${profile==='quest'?'CHECKPOINT':'ESTAÇÃO'} <b id="pv41Now">1</b> / ${count}</span><h2>${title}</h2><div class="pv41-icon">${profile==='quest'?'⚡':'👣'}</div><p id="pv41Instruction">Realize a tarefa orientada pela fisioterapeuta para esta etapa.</p><div class="pv41-time">⏱️ <b id="pv41Time">00:00</b></div><button class="primary" id="pv41Complete" type="button">✓ Etapa concluída</button></div><div class="pv41-finish"><div><span>🏁</span><h3>Percurso concluído</h3><p>Todos os checkpoints foram confirmados.</p><button class="primary" id="pv41Done" type="button">Voltar</button></div></div></div>`;document.body.appendChild(wrap);document.body.style.overflow='hidden';
 const now=q('#pv41Now',wrap),route=q('#pv41Route',wrap),time=q('#pv41Time',wrap),finish=q('.pv41-finish',wrap);let step=0,paused=false,ended=false,pauseAt=0,pausedMs=0;const fmt=ms=>{const sec=Math.floor(ms/1000),m=String(Math.floor(sec/60)).padStart(2,'0'),s=String(sec%60).padStart(2,'0');return `${m}:${s}`;};const draw=()=>{if(!paused&&!ended)time.textContent=fmt(Date.now()-started-pausedMs);route.style.width=(step/count*100)+'%';if(step<count)now.textContent=step+1;};const clock=setInterval(draw,300);draw();
 q('#pv41Complete',wrap).onclick=()=>{if(paused||ended)return;step++;if(step>=count){ended=true;route.style.width='100%';clearInterval(clock);saveStandaloneReport('Missão no Mundo Real',started,count,{checkpoints:count,physicalProfile:profile,physicalTitle:title});setTimeout(()=>finish.classList.add('show'),250);return;}now.textContent=step+1;route.style.width=(step/count*100)+'%';};
 q('#pv41Pause',wrap).onclick=e=>{if(ended)return;paused=!paused;e.currentTarget.textContent=paused?'▶️':'⏸️';if(paused)pauseAt=Date.now();else pausedMs+=Date.now()-pauseAt;q('#pv41Instruction',wrap).textContent=paused?'Pausado. Continue quando estiver pronto.':'Realize a tarefa orientada pela fisioterapeuta para esta etapa.';};
 q('#pv41Back',wrap).onclick=()=>{ended=true;clearInterval(clock);document.body.style.overflow='';wrap.remove();showPhysicalSetup();};q('#pv41Done',wrap).onclick=()=>{document.body.style.overflow='';wrap.remove();showPhysicalSetup();};
}

function addYouthCards(){const grid=q('.youth-card-grid');if(!grid)return;if(!q('[data-youth-breathe]')){const b=document.createElement('button');b.className='youth-card reset-v41';b.type='button';b.dataset.youthBreathe='reset';b.innerHTML=`<span class="youth-card-art v41-youth-art"><img src="assets/relax.webp" alt="Reset"><em>RESET</em></span><span class="youth-card-copy"><strong>Reset</strong><small>Pausa • foco • ritmo respiratório</small></span><span class="youth-card-go">Abrir →</span>`;grid.appendChild(b);}if(!q('[data-youth-physical]')){const b=document.createElement('button');b.className='youth-card movequest-v41';b.type='button';b.dataset.youthPhysical='quest';b.innerHTML=`<span class="youth-card-art v41-move-art"><b>🏁</b><em>MOVE QUEST</em></span><span class="youth-card-copy"><strong>Move Quest</strong><small>Movimento real • sequência • checkpoints</small></span><span class="youth-card-go">Abrir →</span>`;grid.appendChild(b);}}
function enhanceHomeCards(){const br=q('[data-mission="breathe"]'),ph=q('[data-mission="physical"]');if(br){br.classList.add('v41-card-upgraded');const visual=q('.home-v22-visual',br);if(visual)visual.innerHTML='<img class="v41-home-photo" src="assets/relax.webp" alt="Respira Comigo"><span class="v41-home-chip">Calma • Focus • Reset</span>';}if(ph){ph.classList.add('v41-card-upgraded','v41-physical-card');const visual=q('.home-v22-visual',ph);if(visual)visual.innerHTML='<div class="v41-home-route"><i></i><i></i><i></i><b>🏁</b></div><span class="v41-home-chip">Circuito • Move Quest</span>';}}
function boot(){ensureBreatheSetup();ensurePhysicalSetup();addYouthCards();enhanceHomeCards();document.addEventListener('click',e=>{const br=e.target.closest('[data-mission="breathe"]');if(br){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();showBreatheSetup();return;}const ph=e.target.closest('[data-mission="physical"]');if(ph){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();showPhysicalSetup();return;}const yb=e.target.closest('[data-youth-breathe]');if(yb){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();showBreatheSetup('reset');return;}const yp=e.target.closest('[data-youth-physical]');if(yp){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();showPhysicalSetup('quest');}},true);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();