/* Tia Tati Kids — service worker de estabilidade. */
const LEGACY_CACHE='tia-tati-v45-identity-20260910';
const AUDIO_VERSION='kids-audio-v3';
const MUSIC_VERSION='kids-music-v2';
const VOICE_EXPORT_VERSION='voice-export-v2';
const FINAL_CARD_VERSION='completion-v2';
const LAYOUT_VERSION='kids-layout-v13';
const CARDS_UI_VERSION='kids-cards-ui-v8';
const CARDS_EXPORT_VERSION='kids-cards-export-v5';
const GAMES_VERSION='kids-games-v3-clock-refresh';
const CLOCK_VERSION='clock-v6-routine-check-celebration';
const XYLO_VERSION='xylophone-v6-fatima-song';
const XYLO_FATIMA_VERSION='extra-songs-v4-compact-landscape';
const MIRROR_CARD_VERSION='mirror-stable-v1';
self.addEventListener('install',()=>self.skipWaiting());
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k===LEGACY_CACHE||k.startsWith('tia-tati-kids-')).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);
if(/\/tia-tati-kids\/assets\/road-(school|home|park)\.svg$/.test(url.pathname)){event.respondWith(fetch(new Request(event.request.url,{cache:'no-store'})).catch(()=>fetch(event.request,{cache:'reload'})));return}
if(url.pathname.endsWith('/tia-tati-kids/mirror-card-stable-v1.js')){event.respondWith(fetch(event.request,{cache:'no-store'}).catch(()=>fetch(event.request,{cache:'reload'})));return}
if(url.pathname.endsWith('/tia-tati-kids/styles.css')||url.pathname.endsWith('/tia-tati-kids/kids-shell-v1.css')||url.pathname.endsWith('/tia-tati-kids/kids-theme-v2.css')||url.pathname.endsWith('/tia-tati-kids/kids-cards-v8.css')){event.respondWith(fetch(event.request,{cache:'no-store'}).catch(()=>fetch(event.request,{cache:'reload'})));return}
if(url.pathname.endsWith('/tia-tati-kids/kids-games-v1.js')){event.respondWith((async()=>{try{const response=await fetch(new Request(event.request.url,{cache:'no-store'}));if(!response.ok)return response;const source=await response.text();const loader='\n;(()=>{if(!window.__TIA_TATI_CLOCK_LOADER_SW__){window.__TIA_TATI_CLOCK_LOADER_SW__=true;const s=document.createElement("script");s.src="clock-game-v1.js?'+CLOCK_VERSION+'";s.async=true;document.head.appendChild(s)}if(!window.__TIA_TATI_XYLO_LOADER_SW__){window.__TIA_TATI_XYLO_LOADER_SW__=true;const x=document.createElement("script");x.src="xylophone-game-v1.js?'+XYLO_VERSION+'";x.async=true;document.head.appendChild(x)}})();\n';const headers=new Headers(response.headers);headers.set('content-type','application/javascript; charset=utf-8');headers.set('cache-control','no-store, max-age=0');headers.delete('content-length');headers.delete('content-encoding');return new Response(source+loader,{status:response.status,statusText:response.statusText,headers})}catch(_){return fetch(event.request,{cache:'reload'})}})());return}
if(url.pathname.endsWith('/tia-tati-kids/clock-game-v1.js')){event.respondWith((async()=>{try{const response=await fetch(new Request(event.request.url,{cache:'no-store'}));if(!response.ok)return response;const source=await response.text();const loader='\n;(()=>{if(window.__TIA_TATI_XYLO_FROM_CLOCK__)return;window.__TIA_TATI_XYLO_FROM_CLOCK__=true;const x=document.createElement("script");x.src="xylophone-game-v1.js?'+XYLO_VERSION+'";x.async=true;document.head.appendChild(x)})();\n';const headers=new Headers(response.headers);headers.set('content-type','application/javascript; charset=utf-8');headers.set('cache-control','no-store, max-age=0');headers.delete('content-length');headers.delete('content-encoding');return new Response(source+loader,{status:response.status,statusText:response.statusText,headers})}catch(_){return fetch(event.request,{cache:'reload'})}})());return}
if(url.pathname.endsWith('/tia-tati-kids/xylophone-game-v1.js')){event.respondWith((async()=>{try{const response=await fetch(new Request(event.request.url,{cache:'no-store'}));if(!response.ok)return response;const source=await response.text();const loader='\n;(()=>{if(window.__TIA_TATI_XYLO_FATIMA_LOADER__)return;window.__TIA_TATI_XYLO_FATIMA_LOADER__=true;const f=document.createElement("script");f.src="xylophone-fatima-v1.js?'+XYLO_FATIMA_VERSION+'";f.async=true;document.head.appendChild(f)})();\n';const headers=new Headers(response.headers);headers.set('content-type','application/javascript; charset=utf-8');headers.set('cache-control','no-store, max-age=0');headers.delete('content-length');headers.delete('content-encoding');return new Response(source+loader,{status:response.status,statusText:response.statusText,headers})}catch(_){return fetch(event.request,{cache:'reload'})}})());return}
if(url.pathname.endsWith('/tia-tati-kids/xylophone-fatima-v1.js')){event.respondWith(fetch(event.request,{cache:'no-store'}).catch(()=>fetch(event.request,{cache:'reload'})));return}
if(url.pathname.endsWith('/tia-tati-kids/app.js')){event.respondWith((async()=>{try{const response=await fetch(event.request,{cache:'no-store'});if(!response.ok)return response;const source=await response.text();const loader='\n;(()=>{if(window.__TIA_TATI_KIDS_AUDIO_LOADER__)return;window.__TIA_TATI_KIDS_AUDIO_LOADER__=true;const a=document.createElement("script");a.src="kids-audio-v1.js?'+AUDIO_VERSION+'";a.async=true;document.head.appendChild(a);const m=document.createElement("script");m.src="kids-music-v1.js?'+MUSIC_VERSION+'";m.async=true;document.head.appendChild(m);const v=document.createElement("script");v.src="voice-export-v1.js?'+VOICE_EXPORT_VERSION+'";v.async=true;document.head.appendChild(v);const f=document.createElement("script");f.src="final-avatar-v1.js?'+FINAL_CARD_VERSION+'";f.async=true;document.head.appendChild(f);const ce=document.createElement("script");ce.src="kids-cards-export-v1.js?'+CARDS_EXPORT_VERSION+'";ce.async=true;document.head.appendChild(ce);const cu=document.createElement("script");cu.src="kids-cards-ui-v8.js?'+CARDS_UI_VERSION+'";cu.async=true;document.head.appendChild(cu);const mm=document.createElement("script");mm.src="mirror-card-stable-v1.js?'+MIRROR_CARD_VERSION+'";mm.async=true;document.head.appendChild(mm);document.documentElement.dataset.kidsLayout="'+LAYOUT_VERSION+'";})();\n';const headers=new Headers(response.headers);headers.set('content-type','application/javascript; charset=utf-8');headers.set('cache-control','no-store, max-age=0');headers.delete('content-length');headers.delete('content-encoding');return new Response(source+loader,{status:response.status,statusText:response.statusText,headers})}catch(_){return fetch(event.request,{cache:'reload'})}})())}
});