(()=>{
'use strict';
if(window.__TIA_TATI_JOVEM_V21__)return;
window.__TIA_TATI_JOVEM_V21__=true;
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const setText=(el,txt)=>{if(el&&el.textContent!==txt)el.textContent=txt;};
const setHTML=(el,html)=>{if(el&&el.innerHTML!==html)el.innerHTML=html;};
function buildHero(){const home=q('#screen-home'),section=q('.youth-challenges',home||document);if(!home||!section||q('.jovem-home-hero',home))return;const hero=document.createElement('section');hero.className='jovem-home-hero';hero.innerHTML=`<div class="jovem-home-copy"><div style="display:flex;flex-wrap:wrap;gap:8px;align-items:center"><a class="jovem-home-back" href="../tia-tati/?v=21">← Portal Tia Tati</a><a class="jovem-home-back" href="manual-jovem.html?v=21">📘 Manual dos jogos</a></div><span class="jovem-home-kicker">TIA TATI • FISIO SENSORIAL</span><h1>Modo <em>Jovem</em></h1><p>No seu ritmo, você evolui. Desafios terapêuticos com uma linguagem visual mais madura, vibrante e direta.</p><div class="jovem-home-pills"><span>⚡ Resposta</span><span>🧠 Foco</span><span>🎵 Ritmo</span><span>🏁 Autonomia</span></div></div><div class="jovem-home-art" aria-hidden="true"><canvas data-j21-art="react" data-j21-hero="1"></canvas><canvas data-j21-art="beat" data-j21-hero="1"></canvas></div>`;home.insertBefore(hero,section);}
function makeCard(kind,title,desc,art,badge){const b=document.createElement('button');b.className='youth-card '+kind;b.type='button';if(kind==='pulse-lab')b.dataset.youthSensory='pulse';if(kind==='recomeco-j4')b.dataset.youthBreathe='reset';if(kind==='movequest-j4')b.dataset.youthPhysical='quest';b.innerHTML=`<span class="youth-card-art ${kind==='movequest-j4'?'v41-move-art':''}">${kind==='movequest-j4'?'<b>🏁</b>':`<img src="${art}" alt="${title}" decoding="async">`}<em>${badge}</em></span><span class="youth-card-copy"><strong>${title}</strong><small>${desc}</small></span><span class="youth-card-go">Abrir</span>`;return b;}
function ensureSixCards(){const grid=q('.youth-card-grid');if(!grid)return;if(!q('[data-youth-sensory]',grid))grid.appendChild(makeCard('pulse-lab','Laboratório do Pulso','Exploração • foco • causa e efeito','assets/pulse-lab.svg','LABORATÓRIO DO PULSO'));if(!q('[data-youth-breathe]',grid))grid.appendChild(makeCard('recomeco-j4','Recomeço','Pausa • foco • respiração guiada','assets/relax.webp','RECOMEÇO'));if(!q('[data-youth-physical]',grid))grid.appendChild(makeCard('movequest-j4','Missão Movimento','Movimento real • sequência • etapas','','MISSÃO MOVIMENTO'));}
function tuneCards(){const s=q('.youth-challenges');if(!s)return;setText(q('.kicker',s),'DESAFIOS JOVENS');setHTML(q('.youth-challenges-head h2',s),'Escolha seu <span class="jovem-accent">desafio</span> ⚡');setText(q('.youth-challenges-head p',s),'Seis experiências para atenção, ritmo, memória, regulação e movimento.');setText(q('.youth-challenges-tag',s),'Jovens • adultos');[['[data-youth-light="react"]','Reflexo Neon','Resposta rápida • atenção • alcance'],['[data-youth-light="memory"]','Memorize','Sequência visual • memória de trabalho'],['[data-youth-light="beat"]','Ritmo e Movimento','Ritmo • coordenação • tempo de resposta'],['[data-youth-sensory]','Laboratório do Pulso','Exploração • foco • causa e efeito'],['[data-youth-breathe]','Recomeço','Pausa • foco • respiração guiada'],['[data-youth-physical]','Missão Movimento','Movimento real • sequência • etapas']].forEach(([sel,name,desc])=>{const c=q(sel,s);if(!c)return;setText(q('.youth-card-copy strong',c),name);setText(q('.youth-card-copy small',c),desc);setText(q('.youth-card-go',c),'Abrir');});}
function hideSectionContaining(el){const sec=el?.closest('section');if(sec&&!sec.classList.contains('jovem-hide-shared-choice'))sec.classList.add('jovem-hide-shared-choice');}
function isolateSensory(){const s=q('#screen-sensorysetup');if(!s)return;s.classList.add('jovem-shared-screen','jovem-pulse-screen');setText(q('.sensory-v40-head h2',s),'Laboratório do Pulso');setText(q('.sensory-v40-head p',s),'Exploração visual, alcance e causa e efeito em linguagem neon.');setText(q('.mission-badge',s),'⚡ LABORATÓRIO DO PULSO');setHTML(q('.sensory-v40-hero h1',s),'Toque. Conecte.<br><em>Crie seu padrão.</em>');const p=q('[data-sensory-profile="pulse"]',s);if(p){p.classList.add('active');hideSectionContaining(p);}}
function isolateBreathe(){const s=q('#screen-breathesetup');if(!s)return;s.classList.add('jovem-shared-screen','jovem-recomeco-screen');setText(q('.v41-head h2',s),'Recomeço');setText(q('.v41-head p',s),'Pausa guiada, foco e respiração em uma experiência visual jovem.');setText(q('.mission-badge',s),'⚡ RECOMEÇO');setHTML(q('.breathe-v41-hero h1',s),'Pausa. Foco.<br><em>Recomeço.</em>');const m=q('[data-breathe-mode="reset"]',s);if(m){m.classList.add('active');hideSectionContaining(m);}}
function isolatePhysical(){const s=q('#screen-physicalsetup');if(!s)return;s.classList.add('jovem-shared-screen','jovem-movequest-screen');setText(q('.v41-head h2',s),'Missão Movimento');setText(q('.v41-head p',s),'Etapas, sequência e movimento real em uma linguagem de desafio.');setText(q('.mission-badge',s),'🏁 MISSÃO MOVIMENTO');setHTML(q('.physical-v41-hero h1',s),'Movimento.<br><em>Missão. Conquista.</em>');const p=q('[data-physical-profile="quest"]',s);if(p){p.classList.add('active');hideSectionContaining(p);}}
function isolateLight(){const s=q('#screen-lightsetup');if(!s)return;s.classList.add('jovem-shared-screen','jovem-light-screen');setText(q('.light-v18-head p, .light-head p',s),'Escolha a experiência jovem e avance no seu ritmo.');}
function isolateHome(){const home=q('#screen-home');if(!home)return;home.classList.add('jovem-home-only');qa('.home-v22-hero,.home-v22-missions,.kids-v44,.audience-v44,.home-v22-autonomy,.support-v44,.home-v22-cards,.home-v22-tools,.finish-v44,.home-v22-footer-phrase,.home-v22-section-head',home).forEach(el=>el.classList.add('jovem-kids-hidden'));q('#bottomNav')?.classList.add('jovem-nav-hidden');}
function apply(){document.documentElement.classList.add('tia-jovem-v21');isolateHome();ensureSixCards();buildHero();tuneCards();isolateSensory();isolateBreathe();isolatePhysical();isolateLight();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();window.addEventListener('tia:jovem-modules-ready',apply,{once:true});
})();
