(()=>{
  const root=document.getElementById('tangram-levels');if(!root)return;
  const STORE='tangram_rai_performance_v12',CORE_STORE='tangram_prof_junior_mobile_v1',MAX_RECORDS=120;
  let data={records:[]};try{const raw=JSON.parse(localStorage.getItem(STORE)||'{}');if(raw&&Array.isArray(raw.records))data.records=raw.records.slice(-MAX_RECORDS)}catch(e){}
  const save=()=>{try{localStorage.setItem(STORE,JSON.stringify(data))}catch(e){}};
  const coreState=()=>{try{return JSON.parse(localStorage.getItem(CORE_STORE)||'{}')||{}}catch(e){return {}}};
  const secFromClock=v=>{const m=String(v||'').match(/(\d+):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null};
  const clock=s=>{if(s==null||!Number.isFinite(Number(s)))return '—';s=Math.max(0,Math.round(Number(s)));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let toastTimer=null;const toast=msg=>{let el=document.getElementById('tlV12PerfToast');if(!el){el=document.createElement('div');el.id='tlV12PerfToast';el.className='tl-v12-perf-toast';document.body.appendChild(el)}el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2500)};

  const tools=root.querySelector('.tl-brand-tools'),about=root.querySelector('#aboutApp'),perfBtn=document.createElement('button');perfBtn.type='button';perfBtn.id='performanceApp';perfBtn.className='tl-mini-action';perfBtn.innerHTML='📊 <span>Desempenho</span>';if(tools){if(about)tools.insertBefore(perfBtn,about);else tools.appendChild(perfBtn)}
  const overlay=document.createElement('div');overlay.className='tl-v12-perf-overlay';overlay.innerHTML=`<div class="tl-v12-perf-card" role="dialog" aria-modal="true" aria-labelledby="v12PerfTitle"><div class="tl-v12-perf-head"><div><div class="tl-v12-perf-title" id="v12PerfTitle">📊 Meu desempenho</div><div class="tl-v12-perf-sub">Evolução pessoal • dados salvos neste aparelho</div></div><button type="button" class="tl-v12-perf-close" aria-label="Fechar">×</button></div><div class="tl-v12-perf-body"><div id="tlV12PerfContent"></div><div class="tl-v12-perf-actions"><button type="button" id="tlV12MasterOpen" class="primary">🔥 Ir para desafios avançados</button><button type="button" id="tlV12PerfClose">Fechar</button></div></div></div>`;document.body.appendChild(overlay);
  const content=overlay.querySelector('#tlV12PerfContent'),close=()=>overlay.classList.remove('show');overlay.querySelector('.tl-v12-perf-close').addEventListener('click',close);overlay.querySelector('#tlV12PerfClose').addEventListener('click',close);overlay.addEventListener('click',e=>{if(e.target===overlay)close()});
  const achievements=(core,records)=>[['🧩','Primeiro Encaixe','Conclua uma missão.',records.length>=1],['💡','Sem Dicas','Conclua uma partida sem usar dicas.',records.some(r=>r.hints===0)],['🔁','Persistência','Registre 5 conclusões.',records.length>=5],['⭐','Colecionador','Some 15 estrelas no progresso atual.',(core.starsByLevel||[]).reduce((a,b)=>a+(Number(b)||0),0)>=15],['🔥','Mestre das Formas','Conclua as 5 missões clássicas.',(core.completed||[]).filter(i=>i<5).length>=5],['🐉','Lenda R.A.I.','Conclua as 10 missões.',(core.completed||[]).length>=10]];
  const renderPanel=()=>{const core=coreState(),rec=data.records.slice(),completed=new Set(Array.isArray(core.completed)?core.completed:[]),stars=(core.starsByLevel||[]).reduce((a,b)=>a+(Number(b)||0),0),times=rec.map(r=>r.timeSec).filter(Number.isFinite),best=times.length?Math.min(...times):null,avg=times.length?times.reduce((a,b)=>a+b,0)/times.length:null,noHint=rec.filter(r=>r.hints===0).length,byLevel=new Map();rec.forEach(r=>{const k=Number.isInteger(r.level)?r.level:r.name,c=byLevel.get(k);if(!c||r.timeSec<c.timeSec)byLevel.set(k,r)});const bestRows=[...byLevel.values()].sort((a,b)=>(a.level??99)-(b.level??99)).map(r=>`<div class="tl-v12-row"><span>${esc(r.name)}</span><b>${clock(r.timeSec)}</b></div>`).join('')||'<div class="tl-v12-empty">Conclua uma missão para iniciar seu histórico.</div>',recent=rec.slice(-10).reverse().map(r=>`<div class="tl-v12-history"><div><b>${esc(r.name)}</b><small>${esc(r.dateLabel||'Partida registrada')}</small></div><span>${clock(r.timeSec)} • ${r.stars||1}★${r.hints===0?' • sem dica':''}</span></div>`).join('')||'<div class="tl-v12-empty">Nenhuma partida registrada ainda.</div>',badges=achievements(core,rec).map(([ico,name,desc,on])=>`<div class="tl-v12-badge ${on?'on':''}"><span>${ico}</span><div><b>${name}</b><small>${desc}</small></div><em>${on?'✓':'○'}</em></div>`).join('');content.innerHTML=`<div class="tl-v12-summary"><div><b>${completed.size}/10</b><span>missões</span></div><div><b>${stars}</b><span>estrelas</span></div><div><b>${rec.length}</b><span>conclusões</span></div><div><b>${clock(best)}</b><span>melhor tempo</span></div></div><div class="tl-v12-insight"><b>Seu ritmo:</b> ${avg==null?'o histórico começa na primeira conclusão.':`média de ${clock(avg)} por conclusão • ${noHint} partida${noHint===1?'':'s'} sem dicas.`}</div><h4>🏆 Melhores tempos por missão</h4><div class="tl-v12-list">${bestRows}</div><h4>🎖️ Conquistas</h4><div class="tl-v12-badges">${badges}</div><h4>🕘 Histórico recente</h4><div class="tl-v12-list">${recent}</div>`};
  perfBtn.addEventListener('click',()=>{renderPanel();overlay.classList.add('show')});
  const goMaster=()=>{close();const levelsEl=root.querySelector('#levels');if(!levelsEl)return;const buttons=[...levelsEl.querySelectorAll('button.tl-level')],core=coreState(),done=new Set(Array.isArray(core.completed)?core.completed:[]);let idx=5;for(let i=5;i<10;i++){if(!done.has(i)){idx=i;break}else idx=i}const target=buttons[idx]||buttons[5];if(!target)return;target.scrollIntoView({behavior:'smooth',block:'center'});target.classList.add('tl-v12-master-pulse');setTimeout(()=>target.classList.remove('tl-v12-master-pulse'),1200);if(target.disabled){toast('🔥 Conclua a missão anterior para liberar este desafio.');return}setTimeout(()=>target.click(),280)};overlay.querySelector('#tlV12MasterOpen').addEventListener('click',goMaster);
  const levelsEl=root.querySelector('#levels');if(levelsEl){const jump=document.createElement('button');jump.type='button';jump.className='tl-v12-master-jump';jump.innerHTML='🔥 <b>Modo Mestre</b><span>Ir para as fases 6–10</span>';jump.addEventListener('click',goMaster);levelsEl.insertAdjacentElement('afterend',jump)}
  let lastSignature='',lastAt=0;const inspectCompletion=()=>{const msg=root.querySelector('#msg');if(!msg)return;const txt=(msg.textContent||'').replace(/\s+/g,' ').trim();if(!/MISSÃO CONCLUÍDA/i.test(txt))return;const name=(root.querySelector('#title')?.textContent||'Missão').trim(),tm=txt.match(/Tempo:\s*(\d+:\d{2})/i),am=txt.match(/Tentativas:\s*(\d+)/i),hm=txt.match(/Dicas:\s*(\d+)/i),stars=((msg.querySelector('.tl-stars')?.textContent||'').match(/★/g)||[]).length||1,timeSec=secFromClock(tm?.[1]);if(timeSec==null)return;const attempts=Number(am?.[1]||0),hints=Number(hm?.[1]||0),lm=name.match(/^\s*(\d+)/),level=lm?Number(lm[1])-1:null,sig=[name,timeSec,attempts,hints,stars].join('|'),now=Date.now();if(sig===lastSignature&&now-lastAt<5000)return;lastSignature=sig;lastAt=now;const prior=data.records.filter(r=>r.level===level&&Number.isFinite(r.timeSec)),priorBest=prior.length?Math.min(...prior.map(r=>r.timeSec)):null,d=new Date();data.records.push({level,name,timeSec,attempts,hints,stars,at:d.toISOString(),dateLabel:d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'2-digit'})});if(data.records.length>MAX_RECORDS)data.records=data.records.slice(-MAX_RECORDS);save();if(priorBest!=null&&timeSec<priorBest)toast(`🏆 Novo recorde pessoal: ${clock(timeSec)} • ${priorBest-timeSec}s mais rápido`);else if(priorBest==null)toast('📊 Primeira marca registrada nesta missão!')};
  const msg=root.querySelector('#msg');if(msg)new MutationObserver(()=>setTimeout(inspectCompletion,40)).observe(msg,{subtree:true,childList:true,characterData:true,attributes:true});
})();
(()=>{if(!document.querySelector('link[data-rai-tutor]')){const l=document.createElement('link');l.rel='stylesheet';l.href='rai-tutor-v13.css?v=13a';l.dataset.raiTutor='1';document.head.appendChild(l)}if(!document.querySelector('script[data-rai-tutor]')){const s=document.createElement('script');s.src='rai-tutor-v13.js?v=13a';s.dataset.raiTutor='1';document.body.appendChild(s)}})();
