const CACHE='tangram-rai-v12-61';
const ASSETS=['./index.html','./content-v12.json','./manifest.webmanifest','./v10.css','./comfort-v11.css','./focus-v11.css','./performance-v12.css','./app-v10.js','./comfort-v11.js','./performance-v12.js','./rai-tutor-v13.js','./rai-tutor-v13.css','./rai-icon.svg','./rai-aula-v17.js','./rai-aula-v14.css','./rai-aula-v16.css','./rai-aula-v17.css','./rai-fundamentos-v17.json','./rai-pensamento-v17.json','./rai-programacao-v17.json','./rai-matematica-v17.json','./rai-mundo-digital-v17.json','./aulas-entry-v1595.js','./aulas-entry-v1595.css','./prova-parana-v1.js','./prova-parana-v1.css','./prova-parana-subjects.css','./prova-parana-6-v1.json','./prova-parana-7-v1.json','./prova-parana-8a-v1.json','./prova-parana-8b-v1.json','./prova-parana-8c-v1.json','./prova-parana-8d-v1.json','./prova-parana-9-v1.json','./prova-parana-professor-v1.json','./prova-parana-portugues-6-v1.json','./prova-parana-portugues-professor-v1.json','./pp-lp-7-v1.js','./pp-lp-8-v1.js','./pp-lp-9-v1.js','./ios-install-v1.js','./ios-install-v1.css','./gamer-official-v1.js','./gamer-official-v1.css','./shared-ui-v14.css','./identity-v15.css','./update-manager-v14.js','./game-polish-v13.js','./game-polish-v13.css','./icon-192.png','./icon-512.webp','./apple-touch-icon.png','../tangram-prof-junior/rai-chalk.webp','../tangram-prof-junior/chunk01.txt','../tangram-prof-junior/chunk02-03.txt','../tangram-prof-junior/chunk04-05.txt','../tangram-prof-junior/chunk06-07.txt','../tangram-prof-junior/chunk08-09.txt'];
const LIVE_RE=/\/(app-v10\.js|comfort-v11\.js|performance-v12\.js|rai-tutor-v13\.js|rai-aula-v17\.js|aulas-entry-v1595\.js|prova-parana-v1\.js|pp-lp-(?:7|8|9)-v1\.js|ios-install-v1\.js|gamer-official-v1\.js|update-manager-v14\.js|game-polish-v13\.js|v10\.css|comfort-v11\.css|focus-v11\.css|performance-v12\.css|rai-tutor-v13\.css|rai-aula-v14\.css|rai-aula-v16\.css|rai-aula-v17\.css|aulas-entry-v1595\.css|prova-parana-v1\.css|prova-parana-subjects\.css|ios-install-v1\.css|gamer-official-v1\.css|shared-ui-v14\.css|identity-v15\.css|game-polish-v13\.css|rai-icon\.svg|rai-fundamentos-v17\.json|rai-pensamento-v17\.json|rai-programacao-v17\.json|rai-matematica-v17\.json|rai-mundo-digital-v17\.json|prova-parana-(?:6|7|8a|8b|8c|8d|9|professor)-v1\.json|prova-parana-portugues-(?:6|professor)-v1\.json|content-v12\.json|manifest\.webmanifest|icon-192\.png|icon-512\.webp|apple-touch-icon\.png)$/;
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>Promise.all(ASSETS.map(u=>cache.add(u)))).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('tangram-rai-v12-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',event=>{
 if(event.request.method!=='GET')return;
 if(event.request.mode==='navigate'){
  event.respondWith(fetch(event.request,{cache:'no-store'}).then(resp=>{if(!resp||!resp.ok)throw new Error('navigation');const clone=resp.clone();caches.open(CACHE).then(c=>c.put('./index.html',clone)).catch(()=>{});return resp}).catch(()=>caches.match('./index.html')));
  return;
 }
 const u=new URL(event.request.url);
 if(LIVE_RE.test(u.pathname)){
  event.respondWith(fetch(event.request,{cache:'no-store'}).then(resp=>{if(!resp||!resp.ok)throw new Error('asset');const clone=resp.clone();caches.open(CACHE).then(c=>c.put(event.request,clone)).catch(()=>{});return resp}).catch(()=>caches.match(event.request,{ignoreSearch:true})));
  return;
 }
 event.respondWith(caches.match(event.request,{ignoreSearch:true}).then(cached=>cached||fetch(event.request).then(resp=>{if(resp&&resp.ok&&u.origin===self.location.origin){const clone=resp.clone();caches.open(CACHE).then(c=>c.put(event.request,clone)).catch(()=>{})}return resp})));
});
self.addEventListener('message',event=>{if(event.data&&event.data.type==='SKIP_WAITING')self.skipWaiting()});