/* v44 — correct navigation + deterministic devotional interventions */
(function(){
 const $=id=>document.getElementById(id);
 function closeOverlays(){try{speechSynthesis.cancel()}catch(e){}document.querySelectorAll('.modal.open,.intent-modal.open,.dm-journey.open').forEach(x=>x.classList.remove('open'))}
 function showHome(){closeOverlays();$('novena')?.classList.add('hidden');$('portal')?.classList.remove('hidden');document.body.classList.add('dm-home');scrollTo(0,0)}
 function enter(){document.body.classList.remove('dm-home');if(typeof window.enterNovena==='function')window.enterNovena()}
 function afterEnter(fn){enter();setTimeout(fn,40)}
 function currentDay(){return +(localStorage.dmDay||1)}
 function addHome(){let nav=$('novena')?.querySelector('.nav');if(!nav||nav.querySelector('.dm-day-home'))return;let b=document.createElement('button');b.className='dm-day-home';b.innerHTML='<span class="dm-home-icon">⌂</span><span>Início</span>';b.onclick=e=>{e.preventDefault();showHome()};nav.prepend(b)}
 let deferredInstall=null;
 function tools(){document.querySelector('.dm-tools')?.remove();let d=document.createElement('div');d.className='dm-tools';d.innerHTML='<button class="dm-install">⬇ Instalar app</button><button class="dm-share">↗ Compartilhar</button>';$('portal').appendChild(d);d.querySelector('.dm-install').onclick=async e=>{e.preventDefault();if(deferredInstall){deferredInstall.prompt();try{await deferredInstall.userChoice}catch(x){}deferredInstall=null;return}alert(/iphone|ipad|ipod/i.test(navigator.userAgent)?'Toque em Compartilhar e escolha “Adicionar à Tela de Início”.':'Abra o menu ⋮ e escolha “Instalar app” ou “Adicionar à tela inicial”.')};d.querySelector('.dm-share').onclick=async e=>{e.preventDefault();let url='https://joaofaustinojr.github.io/Html/divina-misericordia/',data={title:'Novena da Divina Misericórdia',text:'Reze comigo a Novena da Divina Misericórdia. Jesus, eu confio em Vós.',url};if(navigator.share){try{await navigator.share(data);return}catch(x){if(x.name==='AbortError')return}}location.href='https://wa.me/?text='+encodeURIComponent(data.text+' '+url)}}
 const themes=['O rosto da Misericórdia','Jesus, eu confio em Vós','Das feridas nasce a Misericórdia','Misericórdia para quem está longe','Misericórdia que reconcilia','Pequenez, humildade e confiança','Testemunhas da Misericórdia','Esperança que não morre','Da Polônia para o mundo'];
 function journey(){document.querySelector('.dm-journey')?.remove();let cur=currentDay(),bg=document.createElement('div');bg.className='dm-journey open';bg.innerHTML='<div class="dm-journey-sheet"><header><div><small>MINHA JORNADA</small><h2>Os nove dias</h2><p>Uma caminhada de confiança e misericórdia.</p></div><button class="dm-jclose">×</button></header><div class="dm-journey-line">'+themes.map((t,i)=>{let d=i+1,st=d<cur?'done':d===cur?'current':'';return `<button class="dm-jday ${st}" data-day="${d}"><span class="dm-jnum">${st==='done'?'✓':d}</span><span><b>Dia ${d}</b><em>${t}</em></span><i>›</i></button>`}).join('')+'</div><button class="dm-restart">↺ Recomeçar do início</button></div>';document.body.appendChild(bg);bg.querySelector('.dm-jclose').onclick=()=>bg.remove();bg.querySelectorAll('.dm-jday').forEach(b=>b.onclick=()=>{let d=+b.dataset.day;bg.remove();afterEnter(()=>window.setDay?.(d))});bg.querySelector('.dm-restart').onclick=()=>{localStorage.dmDay='1';bg.remove();afterEnter(()=>window.setDay?.(1))}}
 const img={faustina:'https://commons.wikimedia.org/wiki/Special:FilePath/Saint%20Faustyna%20Kowalska%20portrait%20%281931%29.jpg?width=250',jp2:'https://commons.wikimedia.org/wiki/Special:FilePath/Pope%20John%20Paul%20II%20%281987%29.jpg?width=250',benedict:'https://commons.wikimedia.org/wiki/Special:FilePath/Benedict%20xvi.png?width=250'};
 function portrait(kind,label){let box=document.createElement('div');box.className='dm-person '+kind;box.innerHTML=`<img src="${img[kind]}" alt="${label}" loading="lazy"><span>${label}</span>`;box.querySelector('img').onerror=function(){box.classList.add('dm-image-fallback')};return box}
 function decorate(){let p=$('content');if(!p)return;p.querySelectorAll('.dm-person,.dm-benedict-intervention,.dm-day-emblem').forEach(x=>x.remove());let emblem=document.createElement('div');emblem.className='dm-day-emblem';emblem.innerHTML='<span>✦</span><b>Jezu, ufam Tobie.</b><small>Jesus, eu confio em Vós.</small>';let theme=p.querySelector('.theme');if(theme)theme.after(emblem);p.querySelectorAll('.section').forEach(s=>{let h=s.querySelector('h3');if(!h)return;let t=h.textContent.toLowerCase();s.dataset.icon=/palavra/.test(t)?'✦':/inten/.test(t)?'♡':/vida/.test(t)?'◈':/faustina/.test(t)?'✧':/joão paulo|joao paulo/.test(t)?'✟':'✦';if(/faustina/.test(t))s.prepend(portrait('faustina','Santa Faustina'));if(/joão paulo|joao paulo/.test(t))s.prepend(portrait('jp2','São João Paulo II'))});let jp=[...p.querySelectorAll('.section')].find(s=>/joão paulo|joao paulo/i.test(s.textContent));if(jp){let n=document.createElement('aside');n.className='dm-benedict-intervention';n.appendChild(portrait('benedict','Bento XVI'));let tx=document.createElement('div');tx.innerHTML='<b>Misericórdia e esperança</b><p>A reflexão da Igreja sobre a Divina Misericórdia continuou também no pontificado de Bento XVI, em continuidade com o testemunho de Santa Faustina e São João Paulo II.</p>';n.appendChild(tx);jp.after(n)}}
 function hookRender(){if(typeof window.render!=='function'||window.render.__dm44)return;let old=window.render;window.render=function(){let r=old.apply(this,arguments);requestAnimationFrame(decorate);return r};window.render.__dm44=true;if(typeof window.setDay==='function'&&!window.setDay.__dm44){let sd=window.setDay;window.setDay=function(n){let r=sd.call(this,n);requestAnimationFrame(decorate);return r};window.setDay.__dm44=true}}
 function swipe(){let p=$('content');if(!p||p.dataset.swipe44)return;p.dataset.swipe44='1';let sx=0,sy=0;p.addEventListener('touchstart',e=>{if(e.touches.length===1){sx=e.touches[0].clientX;sy=e.touches[0].clientY}},{passive:true});p.addEventListener('touchend',e=>{let dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;sx=0;if(Math.abs(dx)>=85&&Math.abs(dx)>Math.abs(dy)*1.6)window.go?.(dx<0?1:-1)},{passive:true})}
 function cards(){let bs=document.querySelectorAll('#portal .portal-actions button');if(bs.length<7)return;bs.forEach(b=>{b.removeAttribute('onclick');let c=b.cloneNode(false);b.replaceWith(c)});bs=document.querySelectorAll('#portal .portal-actions button');let f=[enter,()=>afterEnter(()=>openFixed?.()),()=>afterEnter(()=>openChaplet?.()),journey,()=>openMusic?.(),()=>openIntent?.(),()=>showAbout?.()];bs.forEach((b,i)=>b.onclick=e=>{e.preventDefault();e.stopPropagation();f[i]()})}
 function bottom(){document.querySelector('.dm-bottom')?.remove();let n=document.createElement('nav');n.className='dm-bottom';n.innerHTML='<button aria-label="Início"></button><button aria-label="Novena"></button><button aria-label="Orações"></button><button aria-label="Músicas"></button><button aria-label="Reflexões"></button><button aria-label="Mais"></button>';$('portal').appendChild(n);let b=n.querySelectorAll('button');b[0].onclick=showHome;b[1].onclick=enter;b[2].onclick=()=>afterEnter(()=>openFixed?.());b[3].onclick=()=>openMusic?.();b[4].onclick=()=>afterEnter(()=>window.setDay?.(currentDay()));b[5].onclick=()=>showAbout?.()}
 function bind(){if(!$('portal')||!$('novena'))return;window.home=showHome;window.openJourney=journey;addHome();cards();bottom();tools();hookRender();decorate();swipe();showHome()}
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();