/* v42 — Hildegarda-inspired journey + lateral gestures + devotional editorial portraits */
(function(){
 function $(id){return document.getElementById(id)}
 function closeOverlays(){try{window.speechSynthesis&&speechSynthesis.cancel()}catch(e){}document.querySelectorAll('.modal.open,.intent-modal.open,.dm-sheet-bg.open,.dm-auto.open,.dm-journey.open').forEach(function(x){x.classList.remove('open')})}
 function showHome(){closeOverlays();var p=$('portal'),n=$('novena');if(n)n.classList.add('hidden');if(p)p.classList.remove('hidden');document.body.classList.add('dm-home');window.scrollTo(0,0)}
 function enterOnly(){document.body.classList.remove('dm-home');if(typeof window.enterNovena==='function')window.enterNovena()}
 function afterEnter(fn){enterOnly();setTimeout(fn,30)}
 function addHomeToDayNav(){var n=$('novena'),nav=n&&n.querySelector('.nav');if(!nav||nav.querySelector('.dm-day-home'))return;var b=document.createElement('button');b.className='dm-day-home';b.type='button';b.innerHTML='<span class="dm-home-icon">⌂</span><span>Início</span>';b.onclick=function(e){e.preventDefault();showHome()};nav.insertBefore(b,nav.firstChild)}
 var deferredInstall=null;
 function makeTools(){var old=document.querySelector('.dm-tools');if(old)old.remove();var tools=document.createElement('div');tools.className='dm-tools';tools.innerHTML='<button class="dm-install" type="button">⬇ Instalar app</button><button class="dm-share" type="button">↗ Compartilhar</button>';var portal=$('portal');portal.appendChild(tools);var ib=tools.querySelector('.dm-install'),sb=tools.querySelector('.dm-share');ib.onclick=async function(e){e.preventDefault();e.stopPropagation();if(deferredInstall){deferredInstall.prompt();try{await deferredInstall.userChoice}catch(x){}deferredInstall=null;return}alert(/iphone|ipad|ipod/i.test(navigator.userAgent)?'Toque em Compartilhar no navegador e escolha “Adicionar à Tela de Início”.':'Abra o menu ⋮ do navegador e escolha “Instalar app” ou “Adicionar à tela inicial”.')};sb.onclick=async function(e){e.preventDefault();e.stopPropagation();var url='https://joaofaustinojr.github.io/Html/divina-misericordia/',data={title:'Novena da Divina Misericórdia',text:'Reze comigo a Novena da Divina Misericórdia. Jesus, eu confio em Vós.',url:url};if(navigator.share){try{await navigator.share(data);return}catch(x){if(x.name==='AbortError')return}}location.href='https://wa.me/?text='+encodeURIComponent(data.text+' '+url)};window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();deferredInstall=e;ib.classList.add('ready')})}
 var themes=['O rosto da Misericórdia','Jesus, eu confio em Vós','Das feridas nasce a Misericórdia','Misericórdia para quem está longe','Misericórdia que reconcilia','Pequenez, humildade e confiança','Testemunhas da Misericórdia','Esperança que não morre','Da Polônia para o mundo'];
 function openJourney(){var old=document.querySelector('.dm-journey');if(old)old.remove();var cur=+(localStorage.dmDay||1),done=+(localStorage.dmDone||0);var bg=document.createElement('div');bg.className='dm-journey open';var html='<div class="dm-journey-sheet"><header><div><small>MINHA JORNADA</small><h2>Os nove dias</h2><p>Uma caminhada de confiança e misericórdia.</p></div><button class="dm-jclose">×</button></header><div class="dm-journey-line">';themes.forEach(function(t,i){var d=i+1,st=d<cur||d<=done?'done':d===cur?'current':'';html+='<button class="dm-jday '+st+'" data-day="'+d+'"><span class="dm-jnum">'+(st==='done'?'✓':d)+'</span><span><b>Dia '+d+'</b><em>'+t+'</em></span><i>›</i></button>'});html+='</div><button class="dm-restart">↺ Recomeçar do início</button></div>';bg.innerHTML=html;document.body.appendChild(bg);bg.querySelector('.dm-jclose').onclick=function(){bg.remove()};bg.addEventListener('click',function(e){if(e.target===bg)bg.remove()});bg.querySelectorAll('.dm-jday').forEach(function(b){b.onclick=function(){var d=+b.dataset.day;bg.remove();afterEnter(function(){window.setDay&&setDay(d)})}});bg.querySelector('.dm-restart').onclick=function(){localStorage.dmDay='1';localStorage.removeItem('dmDone');bg.remove();afterEnter(function(){window.setDay&&setDay(1)})}}
 var faustina='https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Saint_Faustyna_Kowalska_portrait_%281931%29.jpg/250px-Saint_Faustyna_Kowalska_portrait_%281931%29.jpg';
 var jp2='https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Pope_John_Paul_II_%281987%29.jpg/250px-Pope_John_Paul_II_%281987%29.jpg';
 function decorateDay(){var page=$('content');if(!page)return;page.querySelectorAll('.section').forEach(function(s){var h=s.querySelector('h3');if(!h)return;var t=(h.textContent||'').toLowerCase();s.dataset.icon=t.indexOf('escrit')>-1?'✦':t.indexOf('intenção')>-1?'♡':t.indexOf('vida')>-1?'◈':t.indexOf('terço')>-1?'✝':'✧';if(s.querySelector('.dm-devotional-portrait'))return;var kind=t.indexOf('faustina')>-1?'faustina':(t.indexOf('joão paulo')>-1||t.indexOf('joao paulo')>-1)?'jp2':'';if(kind){var im=document.createElement('img');im.className='dm-devotional-portrait '+kind;im.alt=kind==='faustina'?'Santa Faustina Kowalska':'São João Paulo II';im.src=kind==='faustina'?faustina:jp2;im.loading='lazy';im.onerror=function(){this.remove()};s.classList.add('dm-with-portrait');s.insertBefore(im,h)}})}
 function observeDay(){var page=$('content');if(!page)return;decorateDay();var timer;new MutationObserver(function(){clearTimeout(timer);timer=setTimeout(decorateDay,20)}).observe(page,{childList:true,subtree:true})}
 function swipeDays(){var page=$('content'),sx=0,sy=0;if(!page)return;page.addEventListener('touchstart',function(e){if(e.touches.length!==1)return;sx=e.touches[0].clientX;sy=e.touches[0].clientY},{passive:true});page.addEventListener('touchend',function(e){var dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(Math.abs(dx)<65||Math.abs(dx)<Math.abs(dy)*1.25)return;if(dx<0){window.go&&go(1)}else{window.go&&go(-1)}},{passive:true})}
 function bindCards(){var bs=document.querySelectorAll('#portal .portal-actions button');if(bs.length<7)return;bs.forEach(function(b){b.removeAttribute('onclick');var c=b.cloneNode(false);b.replaceWith(c)});bs=document.querySelectorAll('#portal .portal-actions button');var f=[function(){enterOnly()},function(){afterEnter(function(){window.openFixed&&openFixed()})},function(){afterEnter(function(){window.openChaplet&&openChaplet()})},openJourney,function(){window.openMusic&&openMusic()},function(){window.openIntent&&openIntent()},function(){window.showAbout&&showAbout()}];bs.forEach(function(b,i){b.onclick=function(e){e.preventDefault();e.stopPropagation();f[i]()}})}
 function makeBottomNav(){var old=document.querySelector('.dm-bottom');if(old)old.remove();var nav=document.createElement('nav');nav.className='dm-bottom';nav.innerHTML='<button aria-label="Início"></button><button aria-label="Novena"></button><button aria-label="Orações"></button><button aria-label="Músicas"></button><button aria-label="Reflexões"></button><button aria-label="Mais"></button>';$('portal').appendChild(nav);var b=nav.querySelectorAll('button');b[0].onclick=showHome;b[1].onclick=openJourney;b[2].onclick=function(){afterEnter(function(){openFixed()})};b[3].onclick=function(){window.openMusic&&openMusic()};b[4].onclick=function(){enterOnly()};b[5].onclick=function(){window.showAbout&&showAbout()}}
 function bind(){if(!$('portal')||!$('novena'))return;window.home=showHome;window.openJourney=openJourney;addHomeToDayNav();bindCards();makeBottomNav();makeTools();observeDay();swipeDays();showHome()}
 window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();deferredInstall=e});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();