(()=>{
if(window.__dmMusic16)return;window.__dmMusic16=true;
const tracks=[
 {title:'Improperia — Canto Gregoriano',artist:'Membeth · domínio público',moment:'Paixão de Cristo, súplica e contemplação da Misericórdia.',src:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Improperia.ogg',source:'https://commons.wikimedia.org/wiki/File:Improperia.ogg'},
 {title:'Kyrie — Missa Notre-Dame',artist:'Guillaume de Machaut · gravação em domínio público',moment:'Kyrie eleison — “Senhor, tende piedade”.',src:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Machaut_-_Missa_Notre_Dame_-_Kyrie.ogg',source:'https://commons.wikimedia.org/wiki/File:Machaut_-_Missa_Notre_Dame_-_Kyrie.ogg'},
 {title:'Kyrie — Missa em Dó maior',artist:'Antonio Lotti · gravação em domínio público',moment:'Oração coral para recolhimento e meditação.',src:'https://commons.wikimedia.org/wiki/Special:Redirect/file/LottiCmajKyrie.ogg',source:'https://commons.wikimedia.org/wiki/File:LottiCmajKyrie.ogg'},
 {title:'Johannes Hymnus — Canto Gregoriano',artist:'Membeth · domínio público',moment:'Canto monástico para oração silenciosa.',src:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Johannes.Hymnus.ogg',source:'https://commons.wikimedia.org/wiki/File:Johannes.Hymnus.ogg'}
];
const css=document.createElement('style');css.textContent=`.music-modal{position:fixed;inset:0;z-index:160;background:#030507ed;display:none;align-items:flex-end;justify-content:center;backdrop-filter:blur(6px)}.music-modal.open{display:flex}.music-sheet{box-sizing:border-box;width:min(720px,100%);max-height:94svh;overflow:auto;border:1px solid #b58a4d;border-radius:28px 28px 0 0;padding:22px 18px calc(28px + env(safe-area-inset-bottom));color:#f6eadb;background:linear-gradient(135deg,#35171c,#091015 58%,#10252f);box-shadow:0 -20px 60px #000}.music-head{display:flex;justify-content:space-between;align-items:center}.music-head h2{margin:3px 0;color:#efc36b;font:700 1.55rem Georgia}.music-close{width:40px;height:40px;border-radius:50%;border:1px solid #9c7546;background:#151315;color:#fff;font-size:22px}.music-intro{color:#d8c8b7;line-height:1.45}.music-player{padding:16px;border:1px solid #9e7846;border-radius:20px;background:#080b0e;margin:14px 0}.music-now strong{display:block;color:#f0c76f;font:700 1.08rem Georgia}.music-now span{display:block;color:#cbb9a4;font-size:.78rem;margin:4px 0 13px}.music-player audio{width:100%;height:48px;accent-color:#a8202d}.music-card{width:100%;text-align:left;margin:9px 0;padding:14px;border:1px solid #7e633f;border-radius:17px;background:linear-gradient(120deg,#38191dcc,#10171bcc);color:#f7ead8;font-family:Georgia}.music-card.active{border-color:#e0b65d;background:linear-gradient(120deg,#6d2028cc,#14242bcc)}.music-card strong,.music-card span,.music-card em{display:block}.music-card strong{color:#efc56d}.music-card span{color:#cdbba7;font-size:.78rem;margin-top:3px}.music-card em{font-size:.78rem;line-height:1.4;margin-top:7px}.music-play{display:inline-block;margin-top:9px;border:1px solid #b58a4d;border-radius:14px;padding:6px 10px;background:#a31f2c;font-style:normal}.music-note{color:#b9a996;font-size:.73rem;line-height:1.45;text-align:center}.music-source{color:#d8b875;text-decoration:underline}@media(min-width:800px){.music-modal{align-items:center}.music-sheet{border-radius:28px}}`;document.head.appendChild(css);
let old=document.getElementById('musicModal');if(old)old.remove();const modal=document.createElement('div');modal.id='musicModal';modal.className='music-modal';modal.innerHTML=`<div class="music-sheet"><div class="music-head"><div><small>MÚSICAS PARA REZAR E MEDITAR</small><h2>♫ Player contemplativo</h2></div><button class="music-close">×</button></div><p class="music-intro">Uma pequena seleção de música sacra e monástica com gravações de uso aberto. Sem YouTube, vídeos ou publicidade.</p><div class="music-player"><div class="music-now"><strong id="musicTitle">Escolha um canto</strong><span id="musicArtist">O áudio será reproduzido aqui, dentro da Novena.</span></div><audio id="dmAudio" controls preload="metadata"></audio></div><div>${tracks.map((t,i)=>`<button class="music-card" data-track="${i}"><strong>♫ ${t.title}</strong><span>${t.artist}</span><em>${t.moment}</em><i class="music-play">▶ Reproduzir</i></button>`).join('')}</div><p class="music-note">Fontes: Wikimedia Commons. As faixas acima são identificadas em suas páginas de origem como domínio público. O app não depende de plataformas de vídeo.</p></div>`;document.body.appendChild(modal);const audio=modal.querySelector('#dmAudio'),title=modal.querySelector('#musicTitle'),artist=modal.querySelector('#musicArtist');let current=-1;
function stopNarration(){try{if(typeof stopSpeech==='function')stopSpeech()}catch(e){}try{speechSynthesis.cancel()}catch(e){}}
function loadTrack(i,play=true){const t=tracks[i];if(!t)return;stopNarration();current=i;audio.pause();audio.src=t.src;title.textContent=t.title;artist.textContent=t.artist+' · '+t.moment;modal.querySelectorAll('.music-card').forEach((b,n)=>b.classList.toggle('active',n===i));if(play)audio.play().catch(()=>{})}
window.openMusic=()=>{stopNarration();modal.classList.add('open')};function close(){audio.pause();modal.classList.remove('open')}modal.querySelector('.music-close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};modal.querySelectorAll('.music-card').forEach(b=>b.onclick=()=>loadTrack(+b.dataset.track,true));
})();