(()=>{
if(window.__dmMusic)return;window.__dmMusic=true;
const tracks=[
 {title:'Jezu ufam Tobie',artist:'Mons. Marco Frisina',moment:'Confiança e contemplação.',video:'k3TCl3ZSXE4'},
 {title:'O Ostia Santa',artist:'Mons. Marco Frisina',moment:'Adoração e contemplação eucarística.',video:'99lWtWLWe10'},
 {title:'Misericórdia',artist:'Padre Marcelo Rossi',moment:'Oração pessoal e encerramento.',video:'gmZfUhy1Nl0'}
];
const css=document.createElement('style');css.textContent=`
.music-modal{position:fixed;inset:0;z-index:60;background:rgba(5,7,9,.94);display:none;align-items:flex-end;justify-content:center}.music-modal.open{display:flex}.music-sheet{width:min(760px,100%);max-height:94vh;overflow:auto;border:1px solid rgba(216,174,115,.48);border-radius:25px 25px 0 0;padding:22px 18px calc(28px + env(safe-area-inset-bottom));color:#f6eadb;background:linear-gradient(112deg,rgba(72,23,27,.97),rgba(11,17,21,.98) 54%,rgba(32,54,65,.97));box-shadow:0 -20px 60px #000}.music-sheet:before{content:'';position:fixed;pointer-events:none;inset:0;background:linear-gradient(108deg,transparent 20%,rgba(190,29,43,.16) 43%,transparent 58%),linear-gradient(72deg,transparent 42%,rgba(204,235,248,.14) 59%,transparent 76%)}.music-head,.music-player,.music-list,.music-note{position:relative;z-index:1}.music-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.music-head h2{margin:3px 0 5px;color:#f1d1a4;font-weight:normal}.music-close{width:38px;height:38px;border-radius:50%;border:1px solid #9e7658;background:#201719;color:white;font-size:22px}.music-intro{color:#d8c8b7;line-height:1.5;margin:7px 0 14px}.music-player{border:1px solid rgba(216,174,115,.48);border-radius:20px;overflow:hidden;background:#08090b;box-shadow:0 12px 28px #0008;margin:12px 0 16px}.music-frame{position:relative;aspect-ratio:16/9;background:#08090b}.music-frame iframe{position:absolute;inset:0;width:100%;height:100%;border:0}.music-now{padding:13px 15px;background:linear-gradient(90deg,rgba(111,28,36,.75),rgba(25,38,45,.9))}.music-now strong{display:block;color:#f3d4aa;font-size:1.05rem}.music-now span{display:block;color:#d8c8b7;font-size:.82rem;margin-top:3px}.music-card{width:100%;text-align:left;color:#f7ebdc;margin:9px 0;padding:14px 15px;border-radius:17px;border:1px solid rgba(216,174,115,.38);background:linear-gradient(120deg,rgba(107,31,36,.42),rgba(29,39,44,.54));box-shadow:0 8px 22px #0004;font-family:Georgia,serif}.music-card.active{border-color:#e0b77d;background:linear-gradient(120deg,rgba(142,31,42,.68),rgba(36,54,62,.72))}.music-card strong{display:block;color:#f2d2a6;font-size:1rem;margin-bottom:3px}.music-card span{display:block;color:#d9c9b8;font-size:.82rem}.music-card em{display:block;color:#efe7de;font-size:.8rem;line-height:1.35;margin-top:7px}.music-play{display:inline-block;margin-top:9px;color:#fff;border:1px solid #bd806a;border-radius:18px;padding:6px 10px;background:#9f202c;font-style:normal;font-size:.75rem}.music-note{font-size:.76rem;line-height:1.45;color:#c8b8a7;text-align:center;margin:15px 8px 3px}.music-entry{border-color:#b88968!important}.nav .music-nav{color:#f1c894!important}@media(min-width:800px){.music-modal{align-items:center}.music-sheet{border-radius:25px;max-height:90vh}}
`;document.head.appendChild(css);
const modal=document.createElement('div');modal.id='musicModal';modal.className='music-modal';modal.innerHTML=`<div class="music-sheet"><div class="music-head"><div><div class="kicker">MÚSICAS PARA REZAR E MEDITAR</div><h2>♫ Misericórdia em música</h2></div><button class="music-close" aria-label="Fechar">×</button></div><p class="music-intro">Ouça sem sair da Novena. O player utiliza as gravações disponibilizadas pelos canais oficiais dos artistas.</p><div class="music-player"><div class="music-frame" id="musicFrame"></div><div class="music-now"><strong id="musicTitle"></strong><span id="musicArtist"></span></div></div><div class="music-list">${tracks.map((t,i)=>`<button class="music-card" data-track="${i}"><strong>♫ ${t.title}</strong><span>${t.artist}</span><em>${t.moment}</em><i class="music-play">▶ Ouvir no player</i></button>`).join('')}</div><p class="music-note">A reprodução ocorre dentro do aplicativo por meio do player incorporado do YouTube. Os arquivos de áudio não são copiados nem hospedados pelo app. É necessária conexão com a internet.</p></div>`;document.body.appendChild(modal);
const frame=modal.querySelector('#musicFrame'),title=modal.querySelector('#musicTitle'),artist=modal.querySelector('#musicArtist');let current=-1;
function stopNarration(){try{if(typeof stopSpeech==='function')stopSpeech()}catch(e){}}
function loadTrack(i,autoplay=true){const t=tracks[i];if(!t)return;stopNarration();current=i;frame.innerHTML=`<iframe src="https://www.youtube-nocookie.com/embed/${t.video}?rel=0&playsinline=1${autoplay?'&autoplay=1':''}" title="${t.title}" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>`;title.textContent=t.title;artist.textContent=t.artist+' · '+t.moment;modal.querySelectorAll('.music-card').forEach((b,n)=>b.classList.toggle('active',n===i));}
window.openMusic=()=>{stopNarration();modal.classList.add('open');if(current<0)loadTrack(0,false)};
function close(){modal.classList.remove('open');frame.innerHTML='';current=-1;}
modal.querySelector('.music-close').onclick=close;modal.addEventListener('click',e=>{if(e.target===modal)close()});modal.querySelectorAll('.music-card').forEach(b=>b.onclick=()=>loadTrack(+b.dataset.track,true));
const actions=document.querySelector('.portal-actions');if(actions&&!actions.querySelector('.music-entry')){const b=document.createElement('button');b.className='music-entry';b.innerHTML='♫ Músicas';b.onclick=window.openMusic;const listen=[...actions.querySelectorAll('button')].find(x=>x.textContent.includes('Ouvir'));actions.insertBefore(b,listen||null)}
const nav=document.querySelector('.nav');if(nav&&!nav.querySelector('.music-nav')){const b=document.createElement('button');b.className='music-nav';b.innerHTML='♫ Músicas';b.onclick=window.openMusic;const chap=[...nav.querySelectorAll('button')].find(x=>x.textContent.includes('Terço'));nav.insertBefore(b,chap?chap.nextSibling:null)}
})();